### ISSUE TITLE
What format for input parameters?

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/pmfe#4]
Svetlana:  

The o.nivara mfe structure appears in the file `o.nivara_tRNA.rnasubopt-2280-120--594-370` with `Coefficients:	a = 2280 ≈ 2280,	b = 120 ≈ 120,	c = -594 ≈ -594,
	d = 370 ≈ 370.`

I have some memory that the parameters were "integerized" so tried running
```
PMFEUpdated-2020.09.10-MDS-mschmidt34]$ ./RunPMFECommand.sh pmfe-findmfe --sequence /projects/rna/rnatope/Data/Onivara/fasta/o.nivara_tRNA.fasta -a 2280 -b 120 -c -594 -d 370
```
and, indeed, I do get 
```
(((((((><((((........))))((((((.......))))))>..<(((((.......))))))))))))>	-321/10	-11253
```
All good.  But I also that get same output if I divide all the parameters by 10,  i.e. `-a 228.0 -b 12.0 -c -59.4 -d 37.0` or by 100 or by 1000 -- which seems very unlikely to be correct.  

Does findmfe just ignore the decimals?

**Comment by maxieds** [comment]
@ceheitsch @spoznan:
If this turns out to be a bug that you need me to fix, please let me know and tag with @maxieds so I will get notified of the issue changes.

**Comment by maxieds** [comment]
@ceheitsch @spoznan
Curiosity got the better of me, so I started looking at the ``findmfe`` source code to see if this issue is straightforward to track down. It turns out that there was a slight parsing bug in reading in the decimal-valued parameters. This is a corner case that Christine picked up on with the example above where the decimal approximation really specifies less precision than the trailing zeros appended suggest.

Basically, what the code to rationalize the non-repeating decimal did was split the string at the ``.`` character, and then pick the denominator multiple based on the length of the string to the right of the DOT. Well, this works most of the time, except for when the fractional part input is a zero-valued string or contains trailing zero characters. In the example above, ``input="228.0"; intpart="228"; fracpart="0"``. So the former code thinks that we should rescale by a multiple of ten, when really, the decimal should be approximated by just the integer part. 

## Patches to the PMFE code to fix the problem:

Here is the fixed code from ``src/pmfe_types.cc`` to demonstrate programmatically what the problem and fix to patch it are:
```cpp
Rational get_rational_from_word(std::string word) {
        Rational result;
        std::size_t decimalpoint = word.find('.');
        bool negative = (word.find('-') != std::string::npos);
        if (decimalpoint != std::string::npos) {
            std::string intpart = word.substr(0, decimalpoint);
            std::string fracpart = word.substr(decimalpoint+1);

            if (intpart == "") intpart = "0";
            Integer theint (intpart, 10);
            theint = abs(theint);

            // Carve out the fractional part. Surprisingly fiddly!
            // Handle a corner case where the fractional part is all zeros:
            int fracdenom = 1;
            unsigned int lastNonZeroPos = fracpart.find_last_of("0");
            if(lastNonZeroPos != std::string::npos) {
                 while(lastNonZeroPos != std::string::npos) {
                      fracpart = fracpart.substr(0, lastNonZeroPos);
                      lastNonZeroPos = fracpart.find_last_of("0");
                 }
                 fracdenom = pow(10, fracpart.length());
            }
            Integer fracval (fracpart, 10);
            Rational thefrac (fracval, fracdenom);
            thefrac.canonicalize();

            result = theint + thefrac;
            if (negative) result *= -1;
        } else {
            Rational thevalue (word);
            result = thevalue;
        }
        result.canonicalize();
        return result;
    };
```
With my latest commit to the pull request #2, this patch can be merged with the sources whenever you all have more time to review issue #3. 😃 

## Wrapping up (verifying the difference of outputs between the two initial examples):

Just to verify the outputs, we have the following command generated data:

**(Initial, non-scaled example case):**
```bash
$ ./RunPMFECommand.sh pmfe-findmfe --sequence /projects/rna/rnatope/Data/Onivara/fasta/o.nivara_tRNA.fasta -a 2280 -b 120 -c -594 -d 370 -v


```
**(Second, scaled by 1/10 example case):**
```bash
$ ./RunPMFECommand.sh pmfe-findmfe --sequence /projects/rna/rnatope/Data/Onivara/fasta/o.nivara_tRNA.fasta -a 228.0 -b 12.0 -c -59.4 -d 37.0 -v

```

**Comment by spoznan** [comment]
Christine:

math-mulberry seems to be super slow right now. However, on math-oak when I run
```
./pmfe-findmfe /projects/rna/rnatope/Data/Onivara/fasta/o.nivara_tRNA.fasta -a 2280 -b 120 -c -594 -d 370 
```
I get
```
(((((((><((((........))))((((((.......))))))>..<(((((.......))))))))))))>	1	6	4	-321/10	-11253
```
But when I scale down then parameters by 10 and run
```
./pmfe-findmfe /projects/rna/rnatope/Data/Onivara/fasta/o.nivara_tRNA.fasta -a 228.0 -b 12.0 -c -59.4 -d 37.0 
```
I get
```
(((((((><((((........))))((((((.......))))))>..<(((((.......))))))))))))>	1	6	4	-321/10	-11253/10
```
which makes sense, since the mfe structure should be the same after scaling the energy by a positive parameter, but the total energy is 10 times lower (-11253/10 vs. -11253).

**Comment by maxieds** [comment]
@spoznan 
I updated the binaries on ``math-mulberry`` to use the source code patch I described in my last post here. It is indeed very slow, and still chugging on the ``findmfe`` calculations that I started 2+ hours ago. Nonetheless, you should be able to run the command with the proposed source code fixes I added this afternoon.

I would have to look through the sources again to see exactly how the total energy is getting summed up. You suspect that the total energy of ``-11253/10`` is correct? There would still definitely be some observed hiccups to account for in the previous way (pre-patch) the rational values were getting computed from the fractional part length, which in several of the second cases you just ran above have the trailing zeros. 

Let me know if you want me to look into this more today.

**Comment by ceheitsch** [comment]
@maxieds As @spoznan pointed out, my understanding of the situation was wrong.  If the parameters are all scaled by a constant multiple, then that will *not* after the optimal structure.   It will, however, register in the final output from ```pmfe-findmfe``` and, indeed, I have just confirmed from @spoznan posted output that does.

However, math-mulberry now does *not* have the same output as math-oak did, and the two outputs on math-mulberry do *not* match each other (modulo the factor of 10 in the final position).

```/RunPMFECommand.sh pmfe-findmfe --sequence /projects/rna/rnatope/Data/Onivara/fasta/o.nivara_tRNA.fasta -a 2280 -b 120 -c -594 -d 370```
generates
```(((((((><((((........))))((((((.......))))))>..<(((((.......))))))))))))>	1	6	4	-321/10	-11253``` which agrees with math-oak, but 
```./RunPMFECommand.sh pmfe-findmfe --sequence /projects/rna/rnatope/Data/Onivara/fasta/o.nivara_tRNA.fasta -a 228.0 -b 12.0 -c -59.4 -d 37.0```
gives 
```(((((((><((((........))))((((((.......))))))>..<(((((.......))))))))))))>	1	6	4	-321/10	-11397/10``` which does not.

Please revert whatever change you made it as introduced an error.  Likewise, remove the change from the (still-pending) pull request.   Once both of those have been done, please open a new issue regarding the "corner case" problem that you identified so we can close this one, and track that one separately.  Thanks.

**Comment by ceheitsch** [comment]
@maxieds Having finally had time to look more carefully at the pending pull requests, I see that this change is already a separate one.  (Excellent.)  So I will open a new issue, close this one, and request a modification to the pending pull request.  Please be certain that any changes have been carefully tested.  Thanks!
