### ISSUE TITLE
problems with file input 

### ISSUE THREAD

**Issue by ceheitsch** [gtDMMB/pmfe#5]
The command
```
./RunPMFECommand.sh pmfe-scorer --sequence Examples/o.nivara.fasta --structure Examples/o.nivara_t99_mfe.txt -a 3.4 -b 0 -c 0.4 -d 1
```
generates the error 
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Path "Examples/o.nivara.fasta" does not point to a valid file.
./RunPMFECommand.sh: line 24: 51987 Aborted                 (core dumped) $EXE_PATH/$pmfeCmd $pmfeCmdArgs
```

However, 
```
./RunPMFECommand.sh pmfe-scorer --sequence /projects/rna/rnatope/Data/Onivara/fasta/o.nivara_tRNA.fasta --structure Examples/o.nivara_t99_mfe.txt -a 3.4 -b 0 -c 0.4 -d 1
```
runs fine and terminates with 
```
Multiloops: 0
Unpaired bases: 0
Branches: 0
w: 0 ≈ 0
Parametrized energy: 0 ≈ 0
```
[The fact that this output is not correct is an entirely different issue.]

The file `Examples/o.nivara.fasta` was copied from the other one, and is exactly the same.  Confirmed by the fact that
```
 diff /projects/rna/rnatope/Data/Onivara/fasta/o.nivara_tRNA.fasta Examples/o.nivara.fasta 
```
outputs nothing.

**Comment by maxieds** [comment]
@ceheitsch 
The problem with the command 
```bash
./RunPMFECommand.sh pmfe-scorer --sequence Examples/o.nivara.fasta --structure Examples/o.nivara_t99_mfe.txt -a 3.4 -b 0 -c 0.4 -d 1
```
is that the specified path for the sequence data file (in ``Examples/o.nivara.fasta``) is relative. If you look at the wrapper script I wrote to setup the local paths correctly (file: ``./RunPMFECommand.sh``), it changes directories:
```bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(readlink -f ./GTDMMBSoftware2020/BoostLocalInstall/lib)
export PYTHONPATH=$PYTHONPATH:$(readlink -f ./GTDMMBSoftware2020/pmfe)
export SAGE_PATH=$SAGE_PATH:$PYTHONPATH
export DOT_SAGE=$(readlink -f ./GTDMMBSoftware2020/SageInit)

if [ $# -eq 0 ]; then
        echo "ERROR: Need to pass the argument of the PMFE exe type you wish to run!"
        echo "USAGE: $0 pmfe-sage|pmfe-findmfe|pmfe-parametrizer|pmfe-scorer|pmfe-subopt|pmfe-tests [OPT-ARGS ...]"
        exit -1
fi

EXE_PATH=$(readlink -f ./GTDMMBSoftware2020/pmfe)
cd $EXE_PATH

pmfeCmd=$1
pmfeCmdArgs="${@:2}"
case "${pmfeCmd}" in
        "pmfe-findmfe")      $EXE_PATH/$pmfeCmd $pmfeCmdArgs ;;
        "pmfe-parametrizer") $EXE_PATH/$pmfeCmd $pmfeCmdArgs ;;
        "pmfe-scorer")       $EXE_PATH/$pmfeCmd $pmfeCmdArgs ;;
        "pmfe-subopt")       $EXE_PATH/$pmfeCmd $pmfeCmdArgs ;;
        "pmfe-tests")        $EXE_PATH/$pmfeCmd $pmfeCmdArgs ;;
        "pmfe-sage")         DOT_SAGE=$DOT_SAGE sage         ;;
esac

exit 0
```
The directory change is necessary to run 
```bash
./RunPMFECommand.sh pmfe-tests
```
since the files referenced for the test cases are locally specified to within the ``cd $EXE_PATH`` (set as ``EXE_PATH=$(readlink -f ./GTDMMBSoftware2020/pmfe)``) directory. 

So this means that your second command
```bash
./RunPMFECommand.sh pmfe-scorer --sequence /projects/rna/rnatope/Data/Onivara/fasta/o.nivara_tRNA.fasta --structure Examples/o.nivara_t99_mfe.txt -a 3.4 -b 0 -c 0.4 -d 1
```
will run as intended (modulo the bug for output that is a second issue) because the path ``/projects/rna/rnatope/Data/Onivara/fasta/o.nivara_tRNA.fasta`` for the sequence file is absolute. Apparently the incorrect path for the second sequence is ignored, or possibly just the second time the option is ignored it doesn't register since a sequence has already been specified. I would have to look at the source more carefully to figure out what is going on.

There are then two options that work for me with testing
1. Run (reference the local PMFE example FASTA file): ```./RunPMFECommand.sh pmfe-scorer --sequence test_seq/tRNA/o.nivara_tRNA.fasta --structure Examples/o.nivara_t99_mfe.txt -a 3.4 -b 0 -c 0.4 -d 1```
2. Run (specify a correct relative path after the script directory change): ```./RunPMFECommand.sh pmfe-scorer --sequence ../../Examples/o.nivara.fasta --structure Examples/o.nivara_t99_mfe.txt -a 3.4 -b 0 -c 0.4 -d 1```

One possibility to account for this type of issue in the future would be to add an environment variable that specified the current working directory for the script, e.g., 
```bash
export PMFE_DATA_PATH="$(readlink -f /path/to/fasta/files)"
# ... Run script using this data path ...
unset PMFE_DATA_PATH
# ... Run script with default path setting ...
```
and then set the running directory in the C source with ``cwd(...)`` when this variable is set to a non-empty-string value, or even just set the working directory from within my wrapper script when this variable is set. *Would this be a useful feature to add this week?* Please let me know.

**Comment by ceheitsch** [comment]
Any closing this issue since the file input problems have been explained, but opening another related one regarding setting the current working directory from the shell script.
